Define PRODUCT_DEFAULT_DEV_CERTIFICATE
Change-Id: I64202a4bce45e8bb1c8d01af131488590f5ffab8

diff --git a/tools/opticharger b/tools/opticharger
--- a/tools/opticharger
+++ b/tools/opticharger
@@ -94,42 +94,25 @@ then
     NAME=`basename $1`;
     echo -e $CL_YLW"Optimize:"$CL_RST" $NAME..";
 
-    if [ "$2" != "" ];
+    APKINFO=`grep "name=\"$NAME\"" $APKCERTS`;
+    [ $QUIET ] || echo "APKINFO: $APKINFO";
+    if [ "$APKINFO" = "" ];
     then
-        if [ "$DEFAULT_SYSTEM_DEV_CERTIFICATE" ]; then
-            CERT_PATH=`dirname "$DEFAULT_SYSTEM_DEV_CERTIFICATE"`
-        else
-            CERT_PATH=build/target/product/security
-        fi
-        CERT="$CERT_PATH"/$2.x509.pem
-        KEY="$CERT_PATH"/$2.pk8
-        if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
-        then
-            echo -e $CL_RED"$CERT does not exist!"$CL_RST;
-            exit 1;
-        fi
-    else
-        APKINFO=`grep "name=\"$NAME\"" $APKCERTS`;
-        [ $QUIET ] || echo "APKINFO: $APKINFO";
-        if [ "$APKINFO" = "" ];
-        then
-            echo -e $CL_RED"No apk info for $NAME"$CL_RST;
-            exit 1;
-        fi
-        CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
-        KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
-        if [ "$CERT" = "" ];
-        then
-            echo -e $CL_RED"Unable to find certificate for $NAME"$CL_RST
-            exit 1;
-        fi
-        if [ "$CERT" = "PRESIGNED" ];
-        then
-            echo -e $CL_YLW"$NAME is presigned, skipping"$CL_RST
-            exit 1;
-        fi
+        echo -e $CL_RED"No apk info for $NAME"$CL_RST;
+        exit 1;
     fi
-
+    CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
+    KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
+    if [ "$CERT" = "" ];
+    then
+        echo -e $CL_RED"Unable to find certificate for $NAME"$CL_RST
+        exit 1;
+    fi
+    if [ "$CERT" = "PRESIGNED" ];
+    then
+        echo -e $CL_YLW"$NAME is presigned, skipping"$CL_RST
+        exit 1;
+    fi
     [ $QUIET ] || echo -e $CL_YLW"Certificate:"$CL_RST" $CERT";
 
     [ -d "$TMPDIR/$NAME" ] && rm -rf "$TMPDIR/$NAME"
